import express from "express";
import leadRouter from "../features/leads/lead.routes.js";
import authRouter from "../features/auth/auth.routes.js";
import dealRouter from "../features/deals/deal.routes.js";
import notificationRouter from "../features/notifications/notification.routes.js";
import employeeRouter from "../features/employees/employee.routes.js";
import productRouter from "../features/products/product.routes.js";
import sourceRouter from "../features/sources/source.routes.js";
import descriptionRouter from "../features/descriptions/description.routes.js";
import reminderRouter from "../features/reminders/reminder.routes.js";
import companyRouter from "../features/company/company.routes.js";
import quotationRouter from "../features/quotation/quotation.routes.js";
import permissionRouter from "../features/permissions/permission.routes.js";
import orderRouter from "../features/orders/orders.route.js";
import uploadRouter from "../features/uploads/upload.routes.js";

export const mainRouter = express.Router();

mainRouter.use("/leads", leadRouter);
mainRouter.use("/auth", authRouter);
mainRouter.use("/deals", dealRouter);
mainRouter.use("/notifications", notificationRouter);
mainRouter.use("/employees", employeeRouter);
mainRouter.use("/products", productRouter);
mainRouter.use("/sources", sourceRouter);
mainRouter.use("/descriptions", descriptionRouter);
mainRouter.use("/reminders", reminderRouter);
mainRouter.use("/company", companyRouter);
mainRouter.use("/quotations", quotationRouter);
mainRouter.use("/permissions", permissionRouter);
mainRouter.use("/orders", orderRouter);
mainRouter.use("/drawings", uploadRouter);